ifdef::env-github[]
:toc:
:sectnums:
:sectnumlevels: 1
:sectanchors: 

== Blech's C interface
endif::[]

C can be bound to Blech via annotations.

In principal every Blech declarable entity can be implemented in C. 
Via an annotation a Blech `extern` declaration can be bound to a C implementation. 
It is the responsibility of the programmer to make sure that the C implementation provides what the Blech definition guarantees. 

Currently we support `extern const` and `extern function`.

[source, blech]
----
@[CConst(binding = "5 * A_C_CONST", header = "myconsts.h")]
extern const blech_const
----

`blech_const` is implemented as a C constant.
Assume we have the following macro in `myconsts.h`

[source, c]
----
#define A_C_CONST 42
----

The generated code for the above extern Blech constant is also a macro that requires the include of the appropriate .h-file.

[source, c]
----
// C headers for extern declarations
#include "myconsts.h"

// extern Blech constants
#define blc_blech_const (5 * A_C_CONST)
----

An extern Blech function comes in two flavours.
- 1. As a direct binding too a C function and its .h-file
- 2. As a wrapper to be written in C.

The first case is easy

[source, blech]
----
@[CFunction (binding = "ceil", header = "math.h")]
extern function ceiling(i: float64) returns float64
----

The generated code is again simply a macro.

[source, c]
----
// C headers for extern declarations
#include "math.h"

// extern Blech functions
#define blc_ceiling(blc_i) (ceil(blc_i))
----

The second case defines an extern function without a direct C binding.
Assume the following code in a Blech module `wrapper.blc`

[source, blech]
----
extern function myCFunction(i: float64) returns float64
----

In this case only a prototype is generated in the module's header file `blech/wrapper.h`.

[source, blech]
----
// extern functions to be implemented in C

blc_float64 blc_wrapper_myCFunction (const blc_float64 blc_i);
----

The implementation suitable to the generated prototype has to be provided by the programmer. 
To guarantee the interface the generated .h-file has to be included.


Extern declarations could also be used for `type, typealias, param, var, let, activity` and will be incrementally added.

Since Blech does not allow global variables the local usage of `extern var` and `extern let` creates a "static" local - in the sense of C - and requires the surrounding subprogram or struct declaration to be classified as a `singleton`. 
The same should be necessary for activities written in C that only can represent the state from step to step in global variables which make these activities `singleton` too.