ifdef::env-github[]
:toc:
:sectnums:
:sectnumlevels: 1
:sectanchors: 

:source-highlighter: highlightjs
:highlightjsdir: ../_includes/highlight
:source-language: blech

== Control-flow
endif::[]

=== Model of execution

==== Reactive execution
Unlike classical desktop applications that solve a given task, a Blech application does not run in isolation by itself.
It interacts with a so-called _environment_ that triggers a _reaction_ of the Blech program.

Typically, the environment provides a set of _inputs_ to a Blech program. These inputs may, for example, be sensor readings.
The environment then expects the Blech program to perform some computations and finally return a set of updated _outputs_.
Outputs can be interpreted by the environment, for example, as set points for actuators.

We deliberately use the generic word "environment" because depending on the use case it may have a different form. It ranges from just a loop that calls the Blech application as soon as the last reaction has finished to a sophisticated real-time operating system which manages several tasks, timers and event queues.

The Blech program maintains its state from one reaction to the next.
Thus a reaction does not merely depend on the given inputs but also on the state of the program itself.

==== Synchrony
Blech is a _synchronous_ language.
That means its semantics adhere to the "synchrony assumption".
In simple terms it states that a reaction happens instantaneously (takes no physical time).
Thus program execution proceeds in discrete reactions and there is no observable behaviour in between.

This is of course not implementable in reality but rather a guideline for semantics that has implications on language design and induces a set of crucial properties that make the programmer's life easier.

One implication is that inputs keep their value throughout the reaction. This prevents a volatile behaviour where two readings of the same variable in the same reaction may produce two different values.

The other implication  is that concurrent computations adhere to a https://en.wikipedia.org/wiki/Consistency_model#Strict_consistency[strict consistency] notion.
In essence, this means that "a write to a variable by any thread needs to be seen instantaneously by all threads [...] it assumes concurrent writes to be impossible".
Therefore race conditions are excluded by design.
Since each concurrent thread of execution perceives the others as instantaneous, every shared variable must assume precisely one value throughout the reaction.
It must not be possible for a reader to read two different values for a shared variable within one reaction.
This would discern computation into (at least two) different logical time steps and violate the assumption that the computation happened instantaneously.

This semantics is very attractive to the programmer because concurrent programming becomes simple to understand and debug.
It is the single most crucial distinctive feature of synchronous programming languages in general, and Blech in particular.
Usually in asynchronous, thread-based programming this strict consistency notion is impossible to achieve in practice.
However strict consistency becomes possible in our setting because of two ingredients usually not present in asynchronous concurrent programming:
the distinction of individual reactions; and the distinction of a thread-local view and a global view on a shared memory.

Synchronous languages differ in what programs they admit such that strict consistency is guaranteed. 
Such programs are called causally correct or simply _causal_.
The next section explains what this means for Blech.

==== Causality
The strict consistency memory model excludes write conflicts by definition.
Since we think of program execution as reaction steps, this means causal programs must have at most one writer per shared variable in one reaction.
In Blech we restrict this even further and require that there is at most one writer within a fork-join scope which is potentially executed for multiple reactions.
This is made more precise in the subsequent chapter when we explain the `cobegin` statement.

Furthermore, there is a "thread-local" view of shared variables and a "thread-global" view.
We require that in the thread-global view every shared variable is set to one value by the writer that all other threads may read.
However the writer-thread may update (and read) the variable multiple times locally.
Thus multiple values exist in the thread-local view but they are not observable by concurrent threads nor by the environment and the "illusion" of instantaneous updates is maintained.
Only the last written value is communicated to the concurrent readers.
Of course, "last" is to be understood with respect to the current reaction.
In essence, for every variable there is a write-before-read policy in every reaction.
This allows for normal sequential imperative programming within a thread and at the same time leverages the expressiveness and simplicity of synchronous concurrent programming.
Note that this deliberately excludes programs where threads are mutually (cyclically) dependent within a reaction.

[IMPORTANT]
There is at most one writer per shared variable. The writer must finish its last writing operation to a shared variable in the current reaction before concurrent readers may read it.

The compiler phase that statically ensures a given Blech program is causal is called _causality analysis_.

=== Statements
In its core, Blech is an imperative language.
Blech strictly separates between _statements_ that govern the flow of control and _expressions_ that evaluate to a value.
Both, a statement and an expression may have side-effects.

==== Activities and functions
Control flow is organised with two kinds of procedures: _activities_ and _functions_.
Functions are used like in any other imperative language.
In Blech they have two parameter lists to support causality analysis.
See the section on <<decl:subprogs,subprogram declarations>> for more details.
Functions must terminate within a reaction. Therefore they are said to be instantaneous.

Activities are called similarly to functions but their execution continues until it reaches a pause to end the current reaction.
In the next reaction they resume from the location they have paused and continue execution until the next pause.
Each reaction of an activity must end after finitely many computation steps.
However the activity itself may perform an unbounded number of reactions and never terminate.
It may also terminate after a finite number of reactions.
In nay case, activities must not be instantaneous--they need to pause at least once before termination.
The values of local variables in activities are kept from one reaction to the next.

Activities may call other activities or functions.
Functions however can only call other functions.

==== Synchronous statements
Here we discuss statements that are specific to the synchronous paradigm of Blech.
These statements control the reactive behaviour of the program and hence may only appear inside activities, not in functions.

The aforementioned "pause" is denoted as follows.
[source,abnf]
----
Pause ::= "await" Condition
----
The `await` statement marks the end of a reaction.
The control flow stops at this statement and the program "waits" for the next reaction to start.
Once an activity resumes its execution at an `await` statement the condition is checked.
If it is true, the control flow proceeds to the next statement.
Otherwise, the reaction ends immediately and the control flow remains at the same location.

Example:
[IMPORTANT]
TODO

An activity call is given by the following grammar.
[source,abnf]
----
ActivityCall ::= [(Identifier | Wildcard ) "="] "run" Identifier RhsArgList [LhsArgList]
RhsArgList ::= "()" | "(" RhsExpr ("," RhsExpr)* ")"
LhsArgList ::= "()" | "(" LhsExpr ("," LhsExpr)* ")"
----
The `run` keyword indicates an activity call.
Arguments must be provided that match the callee's declaration in number and type.
If the callee does not declare any outputs the second pair of parentheses may be dropped for readability.
Input arguments must evaluate to a value that matches the declared type.
Output arguments must evaluate to a memory location that the callee can read from and write to.
If the callee is an activity that eventually terminates and declares a return value, this return value must be either received into some variable or ignored using a wildcard.

When control flow reaches a `run` statement the sub-activity is immediately called and the control flow is handed over to the callee.
It remains within the callee for as many reactions as it runs (but at least one reaction).
In every reaction inputs are passed though to the callee and its outputs are propagated outside.
Should the callee terminate, the control flow returns to the caller and proceeds with the next statement.

Example:
[IMPORTANT]
TODO

Concurrent composition is done with the `cobegin` statement.
[source,abnf]
----
ForkJoin ::= "cobegin" ["weak"] StmtBlock ("with" ["weak"] StmtBlock)+ "end"
----
[IMPORTANT]
TODO

There are two kinds of synchronous preemptions built into Blech.
[source,abnf]
----
Preemption ::= "when" Condition ("abort" | "reset") StmtBlock "end"
----
[IMPORTANT]
TODO

==== Imperative control flow
All of the following statements are known from mainstream imperative programming languages.
They may be used inside both, activities and functions.

* assignment
* do...end
* if...then...elseif...end
* while...repeat...end
* repeat...until...end
* return
* function call

[IMPORTANT]
TODO