# Comment baseURL during local testing
baseURL = "https://boschresearch.github.io/blech-doc/"
# This is necessary because of the github projects page, for correct relative URLs
canonifyURLs = true




title = "The Blech language"

publishDir = "../docs"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
# Customization in themes/blech-lang
# theme = ["blech-lang", "docsy"] // no longer necessary
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

#   pygmentsCodeFences = true
#   pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
#   pygmentsUseClassic = true
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
#   pygmentsStyle = "tango"

# [context.production.environment]
# HUGO_ENV = "production"

# Configuration for the Chroma syntax highlighting
# https://gohugo.io/getting-started/configuration-markup/#highlight
# [highlight]
#   codeFences = true
#   hl_Lines = ""
#   lineNoStart = 1
#   lineNos = false
#   lineNumbersInTable = true
#   noClasses = true
#   style = "tango"
#   tabWidth = 4

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-163758392-1"

# Language configuration

[languages]
[languages.en]
title = "Blech"
description = "The Blech language site"
languageName ="English"
# Weight used for sorting.
weight = 1

# [languages.no]
# title = "Goldydocs"
# description = "Docsy er operativsystem for skyen"
# languageName ="Norsk"
# contentDir = "content/no"
# time_format_default = "02.01.2006"
# time_format_blog = "02.01.2006"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Configuration for the Chroma syntax highlighting
# guessSyntax must be true because blech is not known    
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "tango"
    tabWidth = 4

# Everything below this are Site Params

[params]
copyright = "The Blech contributors"
privacy_policy = "/about/privacy-policy/"
# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/boschresearch/blech-doc"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/boschresearch/blech"

# Specify a value here if your content directory is not in your repo's root directory
github_subdir = "website"

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "017078177779977946282:lf6fgveweei"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/boschresearch/blech-doc/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/boschresearch/blech-doc/issues/new">tell us how we can improve</a>.'

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
# [[params.links.user]]
# 	name = "User mailing list"
# 	url = "https://example.org/mail"
# 	icon = "fa fa-envelope"
#         desc = "Discussion and help from your fellow users"
[[params.links.user]]
    name = "The Blech mailing list"
    url = "https://groups.google.com/d/forum/blech-lang"
    icon = "fa fa-envelope"
        desc = "Discuss with other Blech users!"
[[params.links.user]]
    name ="Twitter @BlechLanguage"
    url = "https://twitter.com/BlechLanguage"
    icon = "fab fa-twitter"
    desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
    name ="Documentation on GitHub"
    url = "https://github.com/boschresearch/blech-doc"
    icon = "fas fa-book"
    desc = "Documentation is collected here!"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
    name = "Blech compiler on Github"
    url = "https://github.com/boschresearch/blech"
    icon = "fab fa-github"
        desc = "Compiler development takes place here!"
[[params.links.developer]]
    name = "Blech tools on Github"
    url = "https://github.com/boschresearch/blech-tools"
    icon = "fas fa-tools"
        desc = "Tool development takes place here!"
[[params.links.developer]]
    name = "Collaborate on Slack"
    url = "https://join.slack.com/t/blech-lang/shared_invite/enQtODkyMDg4MDQ2Mjc2LWZjZWI1MmE2NTNhOGU0ZTVmMGEzMzY1ODlmNzBlMDFhMTIwMDRlZDA1MmU2NjY2OTFlZTA1NWIwMzU3NThkY2I"
    icon = "fab fa-slack"
        desc = "Collaborate on Blech development!"

# [[params.links.developer]]
# 	name = "Developer mailing list"
# 	url = "https://example.org/mail"
# 	icon = "fa fa-envelope"
#         desc = "Discuss development issues around the project"

# Privacy settings
# All services disabled

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        disable = true
        # anonymizeIP = true
        # respectDoNotTrack = true
        # useSessionStorage = false
    [privacy.instagram]
        disable = true
    [privacy.twitter]
        disable = true
    [privacy.vimeo]
        disable = true
    [privacy.youtube]
        disable = true

